### ISSUE TITLE
json-menu items don't get matched when rofi is started in combi mode

### ISSUE THREAD

**Issue by michaelkl** [marvinkreis/rofi-json-menu#3]
## Environment
* ArchLinux
* rofi 1.5.4
* rofi-json-menu from git repo (as for https://aur.archlinux.org/packages/rofi-json-menu-git)
* `.config/rofi-json-menu`:
```
{
  "google": {
    "cmd": "xdg-open https://google.com",
    "terminal": false
  }
}
```
## Steps to reproduce
1. **Run rofi** with `combi` mode active:
`rofi -modi "combi,json-menu,run" -show combi -combi-modi "json-menu,run" -no-config`
2. We can see `google` item is here as expected.
3. **Type _"goo"_**: `google` item disappears. ❗🕷️
4. **Clean up** the input and **switch** to the `json-menu` mode (`Shift + Right`).
5. **Type _"goo"_**: `google` item is matched now as expected.
6. **Clean up** the input and **switch back** to the `combi` mode (`Shift + Left`).
7. **Type _"goo"_**: `google` item now is matching here as well.

I've made a small video presentation (recording starts with a black frame):
![s](https://user-images.githubusercontent.com/1443825/72499845-cdd63f80-3854-11ea-82fc-7c0da589aeba.gif)

**Comment by marvinkreis** [comment]
Thanks for the bug report :)

The input matching was implemented in a hackish way that breaks in combi mode. I pushed a commit that should fix it. Please tell me if it works for you now.

**Comment by michaelkl** [comment]
@marvinkreis Works like a charm now! :+1:  
Thanks a lot for such a prompt response!
